version: 0.1

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - docker pull python
  build:
    commands:
      - docker run --name=mypython -p 8000:8000 python:2.7.13-slim
      - ansible-playbook default.yml --syntax-check
      - ansible-playbook default.yml -C
      - ansible-playbook default.yml
  post_build:
    commands:
      - curl 127.0.0.1:8000
