version: 0.1

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - ansible-playbook dev.yml --inventory-file=inventories/hosts --syntax-check
      - ansible-playbook dev.yml --inventory-file=inventories/hosts --check
      - ansible-playbook dev.yml --inventory-file=inventories/hosts
      - curl 127.0.0.1:8000
  post_build:
    commands:
      - echo "end"
